### ISSUE TITLE
attempted to leave type `c64::sid::SIDAudioDevice` uninitialized, which is invalid

### ISSUE THREAD

**Issue by ctrlcctrlv** [kondrak/rust64#21]
```
$ RUST_BACKTRACE=full cargo run prgs/colors.prg
```
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/rust64 prgs/colors.prg`
Read rom/basic.rom: 8192 bytes
Read rom/chargen.rom: 4096 bytes
Read rom/kernal.rom: 8192 bytes
thread 'main' panicked at 'attempted to leave type `c64::sid::SIDAudioDevice` uninitialized, which is invalid', /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/mem/mod.rs:660:9
stack backtrace:
   0:     0x55cd977fbb20 - std::backtrace_rs::backtrace::libunwind::trace::h4dee703919bfd40a
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55cd977fbb20 - std::backtrace_rs::backtrace::trace_unsynchronized::h457e839f1a563e20
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55cd977fbb20 - std::sys_common::backtrace::_print_fmt::h86a55fb30f8393c8
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55cd977fbb20 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7b3d6cac46d277e1
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55cd978126ef - core::fmt::write::h127419eb46f2ecc9
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/fmt/mod.rs:1092:17
   5:     0x55cd977fa105 - std::io::Write::write_fmt::h6010cfbb4726588b
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/io/mod.rs:1578:15
   6:     0x55cd977fd66b - std::sys_common::backtrace::_print::h79b4f9652330cc9d
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55cd977fd66b - std::sys_common::backtrace::print::h330bb326a76af8cf
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55cd977fd66b - std::panicking::default_hook::{{closure}}::heb6a42a7d50a472e
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:208:50
   9:     0x55cd977fd133 - std::panicking::default_hook::h17e521ba6d68d6e1
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:225:9
  10:     0x55cd977fdc1d - std::panicking::rust_panic_with_hook::h70db735e3a6e70cb
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:591:17
  11:     0x55cd977fd7e7 - std::panicking::begin_panic_handler::{{closure}}::h777c71c8e5a7e25c
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:495:13
  12:     0x55cd977fbfdc - std::sys_common::backtrace::__rust_end_short_backtrace::h3e9bf30168899554
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55cd977fd779 - rust_begin_unwind
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:493:5
  14:     0x55cd97774331 - core::panicking::panic_fmt::h5322a082d19786c3
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/panicking.rs:92:14
  15:     0x55cd9777427d - core::panicking::panic::haebb15b6842d6229
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/panicking.rs:50:5
  16:     0x55cd977bbd27 - core::mem::uninitialized::h24e51381cf1d7cc8
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/mem/mod.rs:660:9
  17:     0x55cd977bbd27 - sdl2::audio::AudioDevice<CB>::open_playback::hbb0609a3db1dfcec
                               at /home/fred/.cargo/registry/src/github.com-1ecc6299db9ec823/sdl2-0.25.0/src/sdl2/audio.rs:571:39
  18:     0x55cd97797025 - sdl2::audio::<impl sdl2::sdl::AudioSubsystem>::open_playback::h6be543906219f018
                               at /home/fred/.cargo/registry/src/github.com-1ecc6299db9ec823/sdl2-0.25.0/src/sdl2/audio.rs:74:9
  19:     0x55cd977a5200 - rust64::c64::sid::SID::new_shared::hb9fd972e7558784d
                               at /home/fred/Workspace/rust64/src/c64/sid.rs:149:27
  20:     0x55cd977aa2ad - rust64::c64::C64::new::h19d4a6aba81882f5
                               at /home/fred/Workspace/rust64/src/c64/mod.rs:55:22
  21:     0x55cd9779b713 - rust64::main::h3d420d3cccf68bfa
                               at /home/fred/Workspace/rust64/src/main.rs:40:19
  22:     0x55cd97778dab - core::ops::function::FnOnce::call_once::h296ac6feada574eb
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/ops/function.rs:227:5
  23:     0x55cd97788c9e - std::sys_common::backtrace::__rust_begin_short_backtrace::hbdf6d0329017f8d7
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:125:18
  24:     0x55cd97775e11 - std::rt::lang_start::{{closure}}::h04ebee1a1b54fc53
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/rt.rs:66:18
  25:     0x55cd977fe01a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hbcc915e668c7ca11
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/ops/function.rs:259:13
  26:     0x55cd977fe01a - std::panicking::try::do_call::h6b0f430d48122ddf
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:379:40
  27:     0x55cd977fe01a - std::panicking::try::h6ba420e2e21b5afa
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:343:19
  28:     0x55cd977fe01a - std::panic::catch_unwind::h8366719d1f615eee
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panic.rs:431:14
  29:     0x55cd977fe01a - std::rt::lang_start_internal::h965c28c9ce06ee73
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/rt.rs:51:25
  30:     0x55cd97775df0 - std::rt::lang_start::hfee6940d3a632ed3
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/rt.rs:65:5
  31:     0x55cd9779b97c - main
  32:     0x7fbd32a4ab25 - __libc_start_main
  33:     0x55cd9777499e - _start
  34:                0x0 - <unknown>
```

Update: Tried to debug this on my own. Wasn't able to, but figured out that if I used the `sid::SID` normally reserved for Redox OS (which I guess has no sound) then it works for me, also with no sound. I didn't need sound so I was happy with that. YMMV.

**Comment by ctrlcctrlv** [comment]
Hey, good news, figured out how to use this in 2021! Sound working on desktop Linux!!

Now it's not ideal since @kondrak doesn't seem to work on this anymore and it relies on a deprecated version of Rust-SDL2. But if you patch your Rust-SDL2 v0.25.0 (https://github.com/Rust-SDL2/rust-sdl2/tree/0.26.0 , for some reason no 0.25.0 tag on GitHub) like this:

```
diff --git a/audio.rs b/home/fred/.cargo/registry/src/github.com-1ecc6299db9ec823/sdl2-0.25.0/src/sdl2/audio.rs
index c5982da..0eaeb00 100644
--- a/audio.rs
+++ b/home/fred/.cargo/registry/src/github.com-1ecc6299db9ec823/sdl2-0.25.0/src/sdl2/audio.rs
@@ -558,6 +558,7 @@ pub struct AudioDevice<CB: AudioCallback> {
     userdata: Box<CB>
 }
 
+use std::mem::MaybeUninit;
 impl<CB: AudioCallback> AudioDevice<CB> {
     /// Opens a new audio device given the desired parameters and callback.
     pub fn open_playback<F>(a: &AudioSubsystem, device: Option<&str>, spec: &AudioSpecDesired, get_callback: F) -> Result<AudioDevice <CB>, String>
@@ -568,7 +569,7 @@ impl<CB: AudioCallback> AudioDevice<CB> {
         // callback without the obtained AudioSpec.
         // Create an uninitialized box that will be initialized after SDL_OpenAudioDevice.
         let userdata: *mut CB = unsafe {
-            let b: Box<CB> = Box::new(mem::uninitialized());
+            let b: Box<MaybeUninit<CB>> = Box::new(MaybeUninit::uninit());
             mem::transmute(b)
         };
         let desired = AudioSpecDesired::convert_to_ll(spec.freq, spec.channels, spec.samples, userdata);
```

Then `prgs/playsound.prg` works fine~ :-D

Check it out, running fine even compiled with Rust v1.58, debugger & all!

![image](https://user-images.githubusercontent.com/838783/143007337-241e2453-cadc-4a6d-b959-2280ac279144.png)

**Comment by kondrak** [comment]
I totally forgot about your report :) Thanks for looking into the problem, bumping SDL2 to 0.35.0 was enough to fix the issue (it's now pushed to master).
